Repository Jyotibrat/MarkView, pull requests merged in 2025-02, with the labels that each got.

#105 #98 Completed
  src/Html_Previewer.html
  src/Html_Previewer.js
  src/styles/Html_Previewer.css
Labels: enhancement, acwoc, hard

#100 Fixed Sidebar Visibility issues and Improved the Mobile Navigation
  src/file_upload.html
  src/styles/components.css
Labels: bug, acwoc, medium

#109 #99 Completed
  src/Html_Previewer.html
  src/Html_Previewer.js
  src/script.js
  src/styles/Html_Previewer.css
Labels: bug, acwoc, medium

#112 improvement in ui of home page
  src/styles/base.css
  src/styles/components.css
  src/styles/themes.css
Labels: enhancement, acwoc, easy

#114 #110 Completed
  src/Html_Previewer.html
  src/Html_Previewer.js
  src/styles/Html_Previewer.css
Labels: enhancement, acwoc, medium

#121 clicking on read more button in vision section now leads to vision page
  src/blog.html
Labels: bug, acwoc, medium

#120 #115 Completed navbar updated
  src/navbar.html
  src/styles/components.css
  src/styles/navbar.css
  src/tester.html
Labels: enhancement, acwoc, hard

#123 Navbar link updated
  src/navbar.html
Labels: bug, acwoc, easy

#126 ✨ Added Scroll Button to the Blog Page 🔽✨
  src/blog.html
Labels: enhancement, acwoc, easy

#137 #136 completed cpp ide added
  src/cpp_ide/cpp_ide.css
  src/cpp_ide/cpp_ide.html
  src/cpp_ide_script.js
  src/navbar.html
Labels: enhancement, acwoc, hard
