Repository Jyotibrat/MarkView, pull requests merged in 2025-01, with the labels that each got.

#21 UI improvement
  src/styles.css
Labels: enhancement, good first issue, acwoc, medium

#44 Add Page to Upload and Preview Markdown Files
  src/file_upload.html
  src/index.html
  src/styles.css
Labels: enhancement, acwoc, medium

#73 Updated Readme files in src and styles directories
  src/Readme.md
  src/styles/Readme.md
  src/styles/components.css
Labels: enhancement, acwoc, medium

#74 Major UI/UX Improvements and Mobile Responsiveness Enhancement
  src/about.html
  src/file_upload.html
  src/index.html
  src/navbar.html
  src/script.js
  src/styles/base.css
  src/styles/components.css
Labels: bug, enhancement, acwoc, medium

#89 Update footer.html
  src/footer.html
Labels: enhancement, good first issue, acwoc, easy
